/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 14ac9209f3d5db6df71d0ba0890f20ca)
interface __BaseEnv_CloudflareBindings {
	BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	APP_ENV: string;
	ALLOWED_ORIGINS: string;
	TURNSTILE_EXPECTED_HOSTNAMES: string;
	EMAIL_FROM: string;
	PUBLIC_WEB_URL: string;
	PUBLIC_API_URL: string;
	MP_PUBLIC_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "ALLOWED_ORIGINS" | "TURNSTILE_EXPECTED_HOSTNAMES" | "EMAIL_FROM" | "PUBLIC_WEB_URL" | "PUBLIC_API_URL" | "MP_PUBLIC_KEY">> {}
}
